/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author csalas
 */
public class MainView extends javax.swing.JFrame {
    
    public DefaultTableModel model;
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        this.setSize(640, 480);
        this.setTitle("ImageExtractor");
        manageImageTable();
    }
    
    private void manageImageTable() {
        Object columns[] = {"ID", "NOMBRE", "TAMAÑO", "EXTENSIÓN", "RUTA"};
        model = new DefaultTableModel(columns, 0);
        jTableImage.setModel(model);
        jTableImage.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        
    }
    
    public String getImageFilterSelected() {
        String opt = null;
        for (Enumeration<AbstractButton> buttons = buttonGroup1.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                opt = button.getActionCommand();
            }
        }
        return opt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnIndex = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAreaConsole = new javax.swing.JTextArea();
        jTabbedPanel = new javax.swing.JTabbedPane();
        jPanelImage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableImage = new javax.swing.JTable();
        jTextSearchImage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioImageNombre = new javax.swing.JRadioButton();
        jRadioImageExtension = new javax.swing.JRadioButton();
        jRadioImageRuta = new javax.swing.JRadioButton();
        jPanelMetaData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboDirectorio = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLabels = new javax.swing.JTable();
        btnShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIndex.setText("Indexar");

        jAreaConsole.setEditable(false);
        jAreaConsole.setColumns(20);
        jAreaConsole.setRows(5);
        jScrollPane1.setViewportView(jAreaConsole);

        jTableImage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableImage);

        jLabel1.setText("Filtrar:");

        buttonGroup1.add(jRadioImageNombre);
        jRadioImageNombre.setSelected(true);
        jRadioImageNombre.setText("Nombre");
        jRadioImageNombre.setActionCommand("name");

        buttonGroup1.add(jRadioImageExtension);
        jRadioImageExtension.setText("Extensión");
        jRadioImageExtension.setActionCommand("ext");

        buttonGroup1.add(jRadioImageRuta);
        jRadioImageRuta.setText("Ruta");
        jRadioImageRuta.setActionCommand("path");

        javax.swing.GroupLayout jPanelImageLayout = new javax.swing.GroupLayout(jPanelImage);
        jPanelImage.setLayout(jPanelImageLayout);
        jPanelImageLayout.setHorizontalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioImageNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioImageExtension)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioImageRuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextSearchImage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelImageLayout.setVerticalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSearchImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioImageNombre)
                    .addComponent(jRadioImageExtension)
                    .addComponent(jRadioImageRuta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jTabbedPanel.addTab("Imagen", jPanelImage);

        jLabel2.setText("Directorio:");

        jTableLabels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableLabels);

        javax.swing.GroupLayout jPanelMetaDataLayout = new javax.swing.GroupLayout(jPanelMetaData);
        jPanelMetaData.setLayout(jPanelMetaDataLayout);
        jPanelMetaDataLayout.setHorizontalGroup(
            jPanelMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMetaDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addGroup(jPanelMetaDataLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelMetaDataLayout.setVerticalGroup(
            jPanelMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMetaDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMetaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPanel.addTab("Metadatos", jPanelMetaData);

        btnShow.setText("Recuperar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIndex))
                    .addComponent(jTabbedPanel)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIndex)
                    .addComponent(btnShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIndex;
    public javax.swing.JButton btnShow;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JTextArea jAreaConsole;
    public javax.swing.JComboBox jComboDirectorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanelImage;
    private javax.swing.JPanel jPanelMetaData;
    private javax.swing.JRadioButton jRadioImageExtension;
    private javax.swing.JRadioButton jRadioImageNombre;
    private javax.swing.JRadioButton jRadioImageRuta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPanel;
    public javax.swing.JTable jTableImage;
    public javax.swing.JTable jTableLabels;
    public javax.swing.JTextField jTextSearchImage;
    // End of variables declaration//GEN-END:variables
}
